# Generated by Django 5.0.3 on 2024-03-15 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
        migrations.AlterModelOptions(
            name='about_us',
            options={'verbose_name_plural': 'About Us'},
        ),
    ]
